version: '2'
services:
  web:
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_PROD}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST_PROD}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
     - nginx-proxy
networks:
  nginx-proxy:
    external:
      name: serverservices_default