version: '2'
services:
  web:
    container_name: ${PROJECT_NAME}-dev-node
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_DEV}
    networks:
     - nginx-proxy
networks:
  nginx-proxy:
    external:
      name: serverservices_default
