version: '2'
services:
  web:
    image: node
    container_name: ${PROJECT_NAME}-node
    working_dir: /usr/src/app
    expose:
      - "3000"
    entrypoint:
      - "yarn"
      - "prod"
    restart: always
#     - default
    volumes:
      - "./:/usr/src/app"

#  default:
#    ipam:
#      driver: default
#      config:
#        - subnet: ${SUBNET}